MAC address setting.
Allow the administrator to assign a fixed MAC address to the frontend interface of a pair of backend–frontend VMs.

Useful to designate a static IP address for the frontend interface using NetworkManager or systemd-networkd.

diff --git a/src/vif-route-nexus b/src/vif-route-nexus
--- a/src/vif-route-nexus
+++ b/src/vif-route-nexus
@@ -9,8 +9,7 @@ n=vif-route-nexus
 # via DHCP.
 # pt=/rw/config/nexus-peer-table
 
-logger -t vif-route-qubes "Interface is being managed"
-trap 'logger -t $n "There was an error configuring the VIF"' EXIT
+trap 'logger -t $n "There was an error configuring the VIF $vifname"' EXIT
 
 . /etc/xen/scripts/vif-common.sh
 
@@ -19,6 +18,7 @@ trap 'logger -t $n "There was an error configuring the VIF"' EXIT
 
 if [ "$command" = "online" ] ; then
     if [ "$pt" != "" ] ; then
+        logger -t $n "Interface $vifname is being managed by qubes-arbitrary-network-topology"
         ip link set dev "$vifname" up
         ip=$(grep "^$vifname " "$pt" | awk ' { print $2 } ')
         routes=$(grep "^$vifname " "$pt" | awk ' { print $3 } ')
